### PR TITLE
Rendering

### PR DESCRIPTION
**Pull request by thiblahute**
# review:
- [x] Show you how to state it is done :) (just edit that to add the 'x')
- [x] remove trailing witespaces
- [x] s/ACCEPTABILITY/duration_tolerance/ ?
- [ ] We do not properly see transitions value on schemes in test_transition

Media files generation:
- [x] Check that everything whent ok
- [ ] Make sure we have elements before generating/testing the format
- [ ] You should use gst_check_run_suite instead of srunner_run_all

$make distcheck

```
Unexpected critical/warning: ges_layer_add_asset: assertion `GES_IS_ASSET (asset)' failed
Unexpected critical/warning: ges_layer_add_asset: assertion `GES_IS_ASSET (asset)' failed
Unexpected critical/warning: GError set over the top of a previous GError or uninitialized memory.
This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
The overwriting error message was: Resource not found.
0%: Checks: 6, Failures: 6, Errors: 0
gstcheck.c:75:F:render:test_basic_render:0: Unexpected critical/warning: ges_layer_add_asset: assertion `GES_IS_ASSET (asset)' failed
gstcheck.c:75:F:render:test_effect_rendering:0: Unexpected critical/warning: ges_layer_add_asset: assertion `GES_IS_ASSET (asset)' failed
gstcheck.c:75:F:render:test_transition:0: Unexpected critical/warning: GError set over the top of a previous GError or uninitialized memory.
This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
The overwriting error message was: Resource not found.
gstcheck.c:75:F:render:test_basic_render:0: Unexpected critical/warning: ges_layer_add_asset: assertion   `GES_IS_ASSET (asset)' failed
gstcheck.c:75:F:render:test_effect_rendering:0: Unexpected critical/warning: ges_layer_add_asset: assertion `GES_IS_ASSET (asset)' failed
gstcheck.c:75:F:render:test_transition:0: Unexpected critical/warning: GError set over the top of a previous GError or uninitialized memory.
This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
The overwriting error message was: Resource not found.
FAIL: ges/render
```
- [ ] Make distcheck

This is details and it is very good stuff in overall :)

### CODE REVIEW

**Comment by MathieuDuponchelle** [comment]
thiblahute, I don't know how to represent transitions better in the schemes ?

**Comment by thiblahute** [comment]
Yeah hard stuff :P

```
/**                                                                         
 * Our timeline                                                             
 *        0        1         2         3                                    
 * time   [--------clip------]                                              
 *                 [--trans--]                                              
 *                 [---------clip------]                                    
 */                                                                          
```

**Comment by MathieuDuponchelle** [comment]
yep, it nearly gave me a headache

**Comment by MathieuDuponchelle** [comment]
Ok weird problem: when generating files in the same run as the tests, the first discovery blocks. This can't be reproduced in gdb ...

**Comment by MathieuDuponchelle** [comment]
I just pushed a work in progress commit.

**Pull request closed without merging**
